FROM nginx:latest 
LABEL "author"="mavrick202@gmail.com" "Creation_Date"="March-19" 
RUN apt update
RUN apt install -y unzip net-tools  
RUN apt install -y curl nano
RUN apt install -y unzip jq
COPY index.html /usr/share/nginx/html/
COPY contact.html /usr/share/nginx/html/
COPY scorekeeper.js /usr/share/nginx/html/
ADD style.css /usr/share/nginx/html/
ADD https://releases.hashicorp.com/terraform/1.14.7/terraform_1.14.7_linux_amd64.zip .
ADD https://releases.hashicorp.com/packer/1.15.0/packer_1.15.0_linux_amd64.zip .
RUN unzip terraform_1.14.7_linux_amd64.zip
RUN unzip packer_1.15.0_linux_amd64.zip
RUN mv terraform /usr/local/bin
RUN mv packer /usr/local/bin
RUN rm -rf *.zip
RUN terraform version
RUN packer version
