FROM nginx:latest 
LABEL "author"="satyasai1460@gmail.com" "Creation_Date"="March-19" 
ARG TFORM='1.6.2'
ARG PACK='1.8.1'
ENV AWS_ACCESS_KEY_ID="AKIAIOSFODNN7EXAMPLE"
ENV AWS_SECRET_ACCESS_KEY="wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
ENV AWS_DEFAULT_REGION="us-east-1"
RUN apt update 
RUN apt install -y unzip net-tools \
    && apt install -y curl nano \
    && apt install -y unzip jq iputils-ping \
    && mkdir -p /tmp/terraform /tmp/packer
COPY index.html /usr/share/nginx/html/
COPY contact.html /usr/share/nginx/html/
COPY scorekeeper.js /usr/share/nginx/html/
ADD style.css /usr/share/nginx/html/
ADD https://releases.hashicorp.com/terraform/${TFORM}/terraform_${TFORM}_linux_amd64.zip /tmp/terraform/
ADD https://releases.hashicorp.com/packer/${PACK}/packer_${PACK}_linux_amd64.zip /tmp/packer/
RUN unzip /tmp/terraform/terraform_${TFORM}_linux_amd64.zip -d /tmp/terraform \
    && unzip /tmp/packer/packer_${PACK}_linux_amd64.zip -d /tmp/packer \
    && mv /tmp/terraform/terraform /usr/local/bin \
    && mv /tmp/packer/packer /usr/local/bin \
    && rm -rf /tmp/terraform/*.zip \
    && rm -rf /tmp/packer/*.zip && terraform version && packer version
EXPOSE 80 8080 8000
#CMD ["ping", "-c 3", "www.google.com"]
ENTRYPOINT ["ping", "-c 3", "www.google.com"]
